imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  session.handler.native_file
        save_path: "%kernel.root_dir%/sessions"
        cookie_secure: true
        cookie_httponly: true
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        gitInfo: "@korobi.git_info"
        navigation: "@korobi.navigation_collection"
        theme: "@korobi.theme_service"


# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ 'KorobiWebBundle' ]
    #java: /usr/bin/java
    ruby: /usr/bin/ruby
    sass: "%sass_path%"
    filters:
        cssrewrite: ~
        sass:
            style: compressed
        compass: ~
        scss:
            style: compressed
        uglifyjs2:
            bin: "%uglifyjs_path%"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    assets:
        production:
            inputs:
                - '@KorobiWebBundle/Resources/assets/js/vendor/datepicker.js'
                - '@KorobiWebBundle/Resources/assets/js/vendor/prism.js'
                - '@KorobiWebBundle/Resources/assets/js/vendor/tooltips.js'
                - '@KorobiWebBundle/Resources/assets/js/application/navigation.js'
                - '@KorobiWebBundle/Resources/assets/js/application/irc/log/controls.js'
                - '@KorobiWebBundle/Resources/assets/js/application/irc/log/datepicker.js'
                - '@KorobiWebBundle/Resources/assets/js/application/irc/log/highlighting.js'
                - '@KorobiWebBundle/Resources/assets/js/application/irc/log/tail.js'
        staging:
            inputs:
                - '@KorobiWebBundle/Resources/assets/js/staging/symfony.js'
# Doctrine Configuration
doctrine_mongodb:
    connections:
        default:
            server: "mongodb://%database_host%:%database_port%"
            options: {}
    default_database: "%database_name%"
    document_managers:
        default:
            auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: mongodb
    firewall_name: app
    user_class: Korobi\WebBundle\Document\User
    registration:
        confirmation:
            enabled: false

hwi_oauth:
    firewall_name: app
    resource_owners:
        github:
            type: github
            client_id: "%github_client_id%"
            client_secret: "%github_client_secret%"
    fosub:
        properties:
            github: githubUserId

#Nelmio sec bundle config
nelmio_security:
    csp:
        enforce:
            report-uri: [/csp/report]
            default-src: ['self']
            script-src:
                - 'self'
                - 'https://cdnjs.cloudflare.com'
            font-src:
                - 'self'
                - 'https://cdnjs.cloudflare.com'
                - 'https://fonts.googleapis.com'
                - 'https://fonts.gstatic.com'
            style-src:
                - 'self'
                - 'https://cdnjs.cloudflare.com'
                - 'https://fonts.googleapis.com'
            img-src:
                - 'https:'
                - 'data:'
                - 'http://i.imgur.com'
            media-src:
                - 'https:'
                - 'data:'
                - 'http://i.imgur.com'
            object-src:
                - 'none'
    external_redirects:
        override: /unexpected-redirect
        forward_as: redirUrl
        whitelist:
          - github.com
    content_type:
        nosniff: true
    clickjacking:
        paths:
            '^/docs/.+': SAMEORIGIN
            '^/.*': DENY

