# root node - everything should be nested
korobi_web:
    navigation:
        items:
            - title: home
              route: 'home'

            - title: networks
              route: 'networks'
              routes:
                  - networks
                  - network
                  - channel
                  - channel_command
                  - channel_log
                  - channel_log_date
                  - channel_log_tail
                  - channel_stat

            - title: docs
              route: 'https://docs.korobi.vq.lc/'
              external: true

            - title: about
              route: 'about'

            - title: security
              route: 'security'
              type: 'footer'

            - title: issues
              route: 'https://github.com/korobi/Korobi/issues'
              type: 'footer'
              external: true

            - title: revisions
              route: 'revisions'
              type: 'footer'

    log_cache_directory: %kernel.cache_dir%/korobi/logs/

    homepage_excluded_channels:
       - channel: '#meepmeep22'
         network: 'esper'
       - channel: '#spigot'
         network: 'esper'
       - channel: '#RileyCraft'
         network: 'spigot'
